### PR TITLE
Add small fixes to linreg

### PR DESCRIPTION
**Pull request by JamesYang007**
Change default initial lr to something smaller based on experimentation and tolerance check is now relative

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Nice.  I thought I had already committed the doc header update but had not so will include.

**Comment by JamesYang007** [comment]
Yay (`n=2000, p=1000`):
```
> bench({lm(y~X-1)})
   user  system elapsed 
  0.873   0.000   0.872 

> bench({linear_regression(X,y,rep(0,p), tol=1e-4)})
   user  system elapsed 
  0.957   0.010   0.967 

> bench({linear_regression(X,y,rep(0,p), tol=1e-12)$theta})
   user  system elapsed 
  1.668   0.009   1.678 

> max(abs(lm_coef - my_coef))
[1] 3.918023e-07
```

**Comment by eddelbuettel** [comment]
Yup. I had something similar:

```r
> data(trees)
> X <- as.matrix(cbind(const=1, log(trees[, c("Girth", "Height")])))  # with or without log
> y <- log(trees$Volume)
> coef(summary(lm(y ~ X - 1)))
        Estimate Std. Error  t value    Pr(>|t|)
Xconst  -6.63162  0.7997897 -8.29170 5.05714e-09
XGirth   1.98265  0.0750106 26.43159 2.42255e-21
XHeight  1.11712  0.2044371  5.46439 7.80528e-06
> linear_regression(X, y, rep(0,3))
$loss
[1] 0.185463

$theta
[1] -6.62930  1.98273  1.11654

$gradient
[1]  4.50224e-05  1.49951e-06 -1.12873e-05

$iter
[1] 10

> linear_regression(X, y, rep(0,3), tol=1e-12)
$loss
[1] 0.185463

$theta
[1] -6.63162  1.98265  1.11712

$gradient
[1] 1.82855e-07 4.66718e-07 7.87753e-07

$iter
[1] 18

> 
```

**Comment by eddelbuettel** [comment]
But the 'rough estimate at close to no time difference' is something I'll add to the docs.

**Pull request merged**
